### ISSUE TITLE
Pi and phi the same in readme.md?

### ISSUE THREAD

**Issue by gregsskyles** [hugolgst/digart#1]
Hi Hugo,
It looks like the maps for pi and phi are the same in the image in your readme.md file, at least as far as I can tell by squinting at them. They seem to have the same long and short segments in the same places in the same decants.

**Comment by hugolgst** [comment]
Thanks a lot, you're right. I am going to update that.

**Comment by hugolgst** [comment]
All done!

Here is the new image:
![](https://i.imgur.com/auKLaT2.png)

**Comment by gregsskyles** [comment]
Great! Glad to see that I wasn't imagining things.
